-- hiring-db initial schema (Cloudflare D1 / SQLite).
--
-- GENERATED by scripts/generate_d1_schema.py from models/ — edit the models and
-- regenerate rather than editing this file. tests/test_schema_parity.py fails if
-- this file and Base.metadata drift apart.
--
-- Applied to D1 with:   wrangler d1 migrations apply hiring-db --remote
-- Applied locally with: python -m pipeline.init_db
-- Regenerated with:     python -m scripts.generate_d1_schema
--
-- Type notes for anyone comparing against the old Postgres schema:
--   UUID        -> CHAR(32)  (generated client-side by uuid.uuid4, as before)
--   JSONB       -> JSON      (TEXT affinity; read with json_extract)
--   TIMESTAMPTZ -> DATETIME  (normalized to UTC by models.types.TZDateTime)

CREATE TABLE cip_codes (
	cip_code VARCHAR(9) NOT NULL, 
	cip_title VARCHAR(500) NOT NULL, 
	cip_definition TEXT, 
	level INTEGER NOT NULL, 
	parent_cip_code VARCHAR(9), 
	is_active BOOLEAN NOT NULL, 
	crosswalk_notes TEXT, 
	PRIMARY KEY (cip_code), 
	FOREIGN KEY(parent_cip_code) REFERENCES cip_codes (cip_code)
);

CREATE TABLE occupations (
	onet_soc_code VARCHAR(10) NOT NULL, 
	title VARCHAR(300) NOT NULL, 
	description TEXT, 
	soc_2018_code VARCHAR(8) NOT NULL, 
	job_zone INTEGER, 
	bright_outlook BOOLEAN, 
	PRIMARY KEY (onet_soc_code)
);

CREATE TABLE sources (
	source_id CHAR(32) NOT NULL, 
	source_type VARCHAR(20) NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	base_url VARCHAR(500) NOT NULL, 
	auth_mode VARCHAR(50) NOT NULL, 
	enabled BOOLEAN NOT NULL, 
	politeness_config JSON NOT NULL, 
	terms_reviewed_at DATETIME, 
	PRIMARY KEY (source_id), 
	CONSTRAINT ck_sources_source_type CHECK (source_type IN ('licensed_feed', 'ats_api', 'career_page')), 
	UNIQUE (name)
);

CREATE TABLE companies (
	company_id CHAR(32) NOT NULL, 
	canonical_name VARCHAR(300) NOT NULL, 
	normalized_name VARCHAR(300) NOT NULL, 
	domain VARCHAR(255), 
	hq_state VARCHAR(2), 
	hq_city VARCHAR(200), 
	naics_code VARCHAR(10), 
	size_bucket VARCHAR(50), 
	first_seen_at DATETIME NOT NULL, 
	last_seen_at DATETIME NOT NULL, 
	PRIMARY KEY (company_id)
);

CREATE INDEX ix_companies_normalized_name_domain ON companies (normalized_name, domain);

CREATE TABLE occupation_alt_titles (
	onet_soc_code VARCHAR(10) NOT NULL, 
	alt_title VARCHAR(300) NOT NULL, 
	short_title VARCHAR(300), 
	source VARCHAR(50), 
	PRIMARY KEY (onet_soc_code, alt_title), 
	FOREIGN KEY(onet_soc_code) REFERENCES occupations (onet_soc_code)
);

CREATE TABLE cip_soc_crosswalk (
	cip_code VARCHAR(9) NOT NULL, 
	onet_soc_code VARCHAR(10) NOT NULL, 
	crosswalk_source VARCHAR(50) NOT NULL, 
	retrieved_at VARCHAR(30) NOT NULL, 
	PRIMARY KEY (cip_code, onet_soc_code, crosswalk_source), 
	FOREIGN KEY(cip_code) REFERENCES cip_codes (cip_code), 
	FOREIGN KEY(onet_soc_code) REFERENCES occupations (onet_soc_code)
);

CREATE TABLE raw_documents (
	raw_document_id CHAR(32) NOT NULL, 
	source_id CHAR(32) NOT NULL, 
	doc_type VARCHAR(30) NOT NULL, 
	url VARCHAR(1000) NOT NULL, 
	fetched_at DATETIME NOT NULL, 
	http_status INTEGER, 
	content_type VARCHAR(100), 
	payload_r2_key VARCHAR(120) NOT NULL, 
	payload_bytes INTEGER NOT NULL, 
	payload_sha256 VARCHAR(64) NOT NULL, 
	created_at DATETIME NOT NULL, 
	PRIMARY KEY (raw_document_id), 
	CONSTRAINT ck_raw_documents_doc_type CHECK (doc_type IN ('api_response', 'posting_description', 'html_page')), 
	CONSTRAINT uq_raw_documents_dedupe UNIQUE (source_id, url, doc_type, payload_sha256), 
	FOREIGN KEY(source_id) REFERENCES sources (source_id)
);

CREATE TABLE postings (
	posting_id CHAR(32) NOT NULL, 
	source_id CHAR(32) NOT NULL, 
	source_posting_id VARCHAR(200) NOT NULL, 
	company_id CHAR(32) NOT NULL, 
	title_raw VARCHAR(500) NOT NULL, 
	description_raw_ref CHAR(32) NOT NULL, 
	employment_type VARCHAR(30), 
	is_remote BOOLEAN, 
	location_raw TEXT, 
	location_city VARCHAR(200), 
	location_state VARCHAR(2), 
	location_country VARCHAR(2), 
	us_scope_reason TEXT NOT NULL, 
	posted_at DATETIME, 
	first_seen_at DATETIME NOT NULL, 
	last_seen_at DATETIME NOT NULL, 
	closed_at DATETIME, 
	status VARCHAR(20) NOT NULL, 
	content_hash VARCHAR(64) NOT NULL, 
	PRIMARY KEY (posting_id), 
	CONSTRAINT ck_postings_status CHECK (status IN ('active', 'stale', 'closed')), 
	CONSTRAINT uq_postings_source_posting UNIQUE (source_id, source_posting_id), 
	FOREIGN KEY(source_id) REFERENCES sources (source_id), 
	FOREIGN KEY(company_id) REFERENCES companies (company_id), 
	FOREIGN KEY(description_raw_ref) REFERENCES raw_documents (raw_document_id)
);

CREATE INDEX ix_postings_company_id ON postings (company_id);

CREATE INDEX ix_postings_status ON postings (status);

CREATE TABLE posting_versions (
	posting_version_id CHAR(32) NOT NULL, 
	posting_id CHAR(32) NOT NULL, 
	title_raw VARCHAR(500) NOT NULL, 
	description_raw_ref CHAR(32) NOT NULL, 
	content_hash VARCHAR(64) NOT NULL, 
	recorded_at DATETIME NOT NULL, 
	PRIMARY KEY (posting_version_id), 
	FOREIGN KEY(posting_id) REFERENCES postings (posting_id), 
	FOREIGN KEY(description_raw_ref) REFERENCES raw_documents (raw_document_id)
);

-- Replaces the Postgres pg_trgm GIN index on occupation_alt_titles.alt_title, which
-- has no D1 equivalent. This is a token-based full-text index, not trigram
-- similarity: it answers "which occupations use this title" well, but it cannot
-- produce a graded similarity ratio, so Phase 4's fuzzy tier will need its own
-- confidence scheme rather than scaling a similarity score.
--
-- Populated by pipeline/load_occupations.py, not by triggers — alt titles are
-- bulk-loaded once and never updated in place.
CREATE VIRTUAL TABLE occupation_alt_titles_fts USING fts5(
    alt_title,
    onet_soc_code UNINDEXED,
    tokenize='unicode61 remove_diacritics 2'
);
