-- Student academic profiles (transcript extraction service).
--
-- GENERATED by scripts/generate_d1_schema.py from models/ — edit the models and
-- regenerate rather than editing this file.
--
-- Written by service/profile_store.py after a student reviews what was extracted
-- from their transcript. The uploaded PDF and its extracted text are never stored
-- anywhere — not here, not in raw_documents, not in R2. Only these structured,
-- student-approved fields are, and they are stored verbatim as they appeared in
-- the document (no date or GPA normalization on the way in).

CREATE TABLE student_profiles (
	student_profile_id CHAR(32) NOT NULL, 
	institution VARCHAR(300), 
	degree VARCHAR(300), 
	degree_level VARCHAR(40), 
	major VARCHAR(300), 
	minor VARCHAR(300), 
	concentration VARCHAR(300), 
	graduation_date VARCHAR(60), 
	expected_graduation_date VARCHAR(60), 
	gpa VARCHAR(20), 
	extraction_method VARCHAR(20) NOT NULL, 
	model_version VARCHAR(60), 
	created_at DATETIME NOT NULL, 
	updated_at DATETIME NOT NULL, 
	PRIMARY KEY (student_profile_id), 
	CONSTRAINT ck_student_profiles_extraction_method CHECK (extraction_method IN ('llm', 'rules', 'manual'))
);

CREATE TABLE student_courses (
	student_course_id CHAR(32) NOT NULL, 
	student_profile_id CHAR(32) NOT NULL, 
	course_code VARCHAR(40), 
	course_name VARCHAR(200), 
	credits FLOAT, 
	grade VARCHAR(10), 
	term VARCHAR(40), 
	student_approved BOOLEAN NOT NULL, 
	position INTEGER NOT NULL, 
	PRIMARY KEY (student_course_id), 
	FOREIGN KEY(student_profile_id) REFERENCES student_profiles (student_profile_id)
);

CREATE INDEX ix_student_courses_profile_id ON student_courses (student_profile_id);

CREATE TABLE student_attributes (
	student_attribute_id CHAR(32) NOT NULL, 
	student_profile_id CHAR(32) NOT NULL, 
	attribute_type VARCHAR(20) NOT NULL, 
	value VARCHAR(300) NOT NULL, 
	position INTEGER NOT NULL, 
	PRIMARY KEY (student_attribute_id), 
	CONSTRAINT ck_student_attributes_attribute_type CHECK (attribute_type IN ('skill', 'honor', 'certification')), 
	FOREIGN KEY(student_profile_id) REFERENCES student_profiles (student_profile_id)
);

CREATE INDEX ix_student_attributes_type ON student_attributes (attribute_type);

CREATE INDEX ix_student_attributes_profile_id ON student_attributes (student_profile_id);
