"""create sources, companies, raw_documents, postings, posting_versions

Revision ID: 0371afd22a03
Revises: 282593a6d575
Create Date: 2026-08-14 22:42:39.032234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0371afd22a03'
down_revision: Union[str, Sequence[str], None] = '282593a6d575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('hq_state', sa.String(length=2), nullable=True),
    sa.Column('hq_city', sa.String(length=200), nullable=True),
    sa.Column('naics_code', sa.String(length=10), nullable=True),
    sa.Column('size_bucket', sa.String(length=50), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index('ix_companies_normalized_name_domain', 'companies', ['normalized_name', 'domain'], unique=False)
    op.create_table('sources',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('auth_mode', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('politeness_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('terms_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("source_type IN ('licensed_feed', 'ats_api', 'career_page')", name='ck_sources_source_type'),
    sa.PrimaryKeyConstraint('source_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('raw_documents',
    sa.Column('raw_document_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("doc_type IN ('api_response', 'posting_description', 'html_page')", name='ck_raw_documents_doc_type'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('raw_document_id'),
    sa.UniqueConstraint('source_id', 'url', 'doc_type', 'payload_sha256', name='uq_raw_documents_dedupe')
    )
    op.create_table('postings',
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_posting_id', sa.String(length=200), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title_raw', sa.String(length=500), nullable=False),
    sa.Column('description_raw_ref', sa.UUID(), nullable=False),
    sa.Column('employment_type', sa.String(length=30), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('location_raw', sa.Text(), nullable=True),
    sa.Column('location_city', sa.String(length=200), nullable=True),
    sa.Column('location_state', sa.String(length=2), nullable=True),
    sa.Column('location_country', sa.String(length=2), nullable=True),
    sa.Column('us_scope_reason', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint("status IN ('active', 'stale', 'closed')", name='ck_postings_status'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['description_raw_ref'], ['raw_documents.raw_document_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.source_id'], ),
    sa.PrimaryKeyConstraint('posting_id'),
    sa.UniqueConstraint('source_id', 'source_posting_id', name='uq_postings_source_posting')
    )
    op.create_table('posting_versions',
    sa.Column('posting_version_id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.Column('title_raw', sa.String(length=500), nullable=False),
    sa.Column('description_raw_ref', sa.UUID(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['description_raw_ref'], ['raw_documents.raw_document_id'], ),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.posting_id'], ),
    sa.PrimaryKeyConstraint('posting_version_id')
    )
    # NOTE: autogenerate flags ix_occupation_alt_titles_alt_title_trgm as "removed"
    # because it was created via raw SQL (op.execute) rather than an Index construct
    # in models/occupation.py, so it isn't in SQLAlchemy metadata. It's untouched here.
    op.create_index('ix_postings_company_id', 'postings', ['company_id'], unique=False)
    op.create_index('ix_postings_status', 'postings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_postings_status', table_name='postings')
    op.drop_index('ix_postings_company_id', table_name='postings')
    op.drop_table('posting_versions')
    op.drop_table('postings')
    op.drop_table('raw_documents')
    op.drop_table('sources')
    op.drop_index('ix_companies_normalized_name_domain', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
