"""create occupations, occupation_alt_titles, cip_soc_crosswalk

Revision ID: 282593a6d575
Revises: 6d1690daf7ac
Create Date: 2026-08-12 09:58:59.216036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '282593a6d575'
down_revision: Union[str, Sequence[str], None] = '6d1690daf7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupations',
    sa.Column('onet_soc_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('soc_2018_code', sa.String(length=8), nullable=False),
    sa.Column('job_zone', sa.Integer(), nullable=True),
    sa.Column('bright_outlook', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('onet_soc_code')
    )
    op.create_table('cip_soc_crosswalk',
    sa.Column('cip_code', sa.String(length=9), nullable=False),
    sa.Column('onet_soc_code', sa.String(length=10), nullable=False),
    sa.Column('crosswalk_source', sa.String(length=50), nullable=False),
    sa.Column('retrieved_at', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['cip_code'], ['cip_codes.cip_code'], ),
    sa.ForeignKeyConstraint(['onet_soc_code'], ['occupations.onet_soc_code'], ),
    sa.PrimaryKeyConstraint('cip_code', 'onet_soc_code', 'crosswalk_source')
    )
    op.create_table('occupation_alt_titles',
    sa.Column('onet_soc_code', sa.String(length=10), nullable=False),
    sa.Column('alt_title', sa.String(length=300), nullable=False),
    sa.Column('short_title', sa.String(length=300), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['onet_soc_code'], ['occupations.onet_soc_code'], ),
    sa.PrimaryKeyConstraint('onet_soc_code', 'alt_title')
    )
    # Trigram index for fuzzy title matching (Phase 4 classification, tier 2).
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        "CREATE INDEX ix_occupation_alt_titles_alt_title_trgm "
        "ON occupation_alt_titles USING gin (alt_title gin_trgm_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_occupation_alt_titles_alt_title_trgm")
    op.drop_table('occupation_alt_titles')
    op.drop_table('cip_soc_crosswalk')
    op.drop_table('occupations')
    # ### end Alembic commands ###
