"""create cip_codes table

Revision ID: 6d1690daf7ac
Revises: 
Create Date: 2026-08-12 01:40:54.291841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d1690daf7ac'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cip_codes',
    sa.Column('cip_code', sa.String(length=9), nullable=False),
    sa.Column('cip_title', sa.String(length=500), nullable=False),
    sa.Column('cip_definition', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_cip_code', sa.String(length=9), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('crosswalk_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['parent_cip_code'], ['cip_codes.cip_code'], ),
    sa.PrimaryKeyConstraint('cip_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cip_codes')
    # ### end Alembic commands ###
