"""Regenerate migrations/d1/*.sql from the ORM metadata.

The checked-in .sql files are the source of truth applied to both D1 and the local
SQLite database — this script is how they get written, so the DDL and `Base.metadata`
can never disagree by hand. `tests/test_schema_parity.py` enforces that they still
agree after any model change.

**Why more than one file.** Migrations are applied by name and tracked in a ledger
(`d1_migrations`), so a file that has already been applied to the remote database
will never be re-run — editing it silently does nothing. New tables therefore go
into a new file, and every earlier file must regenerate byte-identically. MIGRATIONS
below is that mapping; adding a model without adding it there is an error, not a
silent omission.

Run as: python -m scripts.generate_d1_schema
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

from sqlalchemy import create_mock_engine

from models import Base  # importing the package registers every mapper

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = REPO_ROOT / "migrations" / "d1"

INITIAL_HEADER = """\
-- hiring-db initial schema (Cloudflare D1 / SQLite).
--
-- GENERATED by scripts/generate_d1_schema.py from models/ — edit the models and
-- regenerate rather than editing this file. tests/test_schema_parity.py fails if
-- this file and Base.metadata drift apart.
--
-- Applied to D1 with:   wrangler d1 migrations apply hiring-db --remote
-- Applied locally with: python -m pipeline.init_db
-- Regenerated with:     python -m scripts.generate_d1_schema
--
-- Type notes for anyone comparing against the old Postgres schema:
--   UUID        -> CHAR(32)  (generated client-side by uuid.uuid4, as before)
--   JSONB       -> JSON      (TEXT affinity; read with json_extract)
--   TIMESTAMPTZ -> DATETIME  (normalized to UTC by models.types.TZDateTime)
"""

FTS5 = """\

-- Replaces the Postgres pg_trgm GIN index on occupation_alt_titles.alt_title, which
-- has no D1 equivalent. This is a token-based full-text index, not trigram
-- similarity: it answers "which occupations use this title" well, but it cannot
-- produce a graded similarity ratio, so Phase 4's fuzzy tier will need its own
-- confidence scheme rather than scaling a similarity score.
--
-- Populated by pipeline/load_occupations.py, not by triggers — alt titles are
-- bulk-loaded once and never updated in place.
CREATE VIRTUAL TABLE occupation_alt_titles_fts USING fts5(
    alt_title,
    onet_soc_code UNINDEXED,
    tokenize='unicode61 remove_diacritics 2'
);
"""

STUDENT_HEADER = """\
-- Student academic profiles (transcript extraction service).
--
-- GENERATED by scripts/generate_d1_schema.py from models/ — edit the models and
-- regenerate rather than editing this file.
--
-- Written by service/profile_store.py after a student reviews what was extracted
-- from their transcript. The uploaded PDF and its extracted text are never stored
-- anywhere — not here, not in raw_documents, not in R2. Only these structured,
-- student-approved fields are, and they are stored verbatim as they appeared in
-- the document (no date or GPA normalization on the way in).
"""


@dataclass(frozen=True)
class Migration:
    filename: str
    header: str
    tables: tuple[str, ...]
    # Raw SQL appended after the generated statements, for objects SQLAlchemy
    # cannot model (currently just the FTS5 virtual table).
    trailer: str = ""


MIGRATIONS: tuple[Migration, ...] = (
    Migration(
        filename="0001_initial.sql",
        header=INITIAL_HEADER,
        tables=(
            "cip_codes",
            "occupations",
            "occupation_alt_titles",
            "cip_soc_crosswalk",
            "sources",
            "companies",
            "raw_documents",
            "postings",
            "posting_versions",
        ),
        trailer=FTS5,
    ),
    Migration(
        filename="0002_student_profiles.sql",
        header=STUDENT_HEADER,
        tables=("student_profiles", "student_courses", "student_attributes"),
    ),
)


def _check_coverage() -> None:
    """Every mapped table must belong to exactly one migration file.

    Without this, adding a model and forgetting to place it here would produce a
    schema that passes generation, fails `test_schema_parity`, and — if that test
    were ever skipped — reach D1 missing a table.
    """
    mapped = set(Base.metadata.tables)
    placed: set[str] = set()
    duplicates: list[str] = []

    for migration in MIGRATIONS:
        for table in migration.tables:
            if table in placed:
                duplicates.append(table)
            placed.add(table)

    if duplicates:
        raise SystemExit(f"tables listed in more than one migration: {sorted(set(duplicates))}")
    missing = sorted(mapped - placed)
    if missing:
        raise SystemExit(
            f"tables in models/ but not assigned to a migration: {missing}\n"
            "Add them to a NEW Migration entry in scripts/generate_d1_schema.py — never to an "
            "already-applied one, which the d1_migrations ledger will refuse to re-run."
        )
    unknown = sorted(placed - mapped)
    if unknown:
        raise SystemExit(f"tables assigned to a migration but not present in models/: {unknown}")


def render(migration: Migration) -> str:
    statements: list[str] = []

    def collect(sql, *args, **kwargs) -> None:
        text = str(sql.compile(dialect=engine.dialect)).strip()
        statements.append(f"{text};")

    engine = create_mock_engine("sqlite://", collect)
    Base.metadata.create_all(
        engine,
        tables=[Base.metadata.tables[name] for name in migration.tables],
        checkfirst=False,
    )

    return migration.header + "\n" + "\n\n".join(statements) + "\n" + migration.trailer


def main() -> None:
    _check_coverage()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for migration in MIGRATIONS:
        path = OUTPUT_DIR / migration.filename
        path.write_text(render(migration), encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
